// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataBaseFirstApproach.Context;
using DataBaseFirstApproach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DataBaseFirstApproach.Context.Configurations
{
    public partial class EmployeeDepartmentConfiguration : IEntityTypeConfiguration<EmployeeDepartment>
    {
        public void Configure(EntityTypeBuilder<EmployeeDepartment> entity)
        {
            entity.ToView("EmployeeDepartment");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmployeeDepartment> entity);
    }
}
